### ISSUE TITLE
Commodity types: Metadata

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourceprojects.org#19]
A second example of a metadata / code list challenge. 

The extractives community / INGO's do not share use of a standardised taxonomy for commodity types. 

1) The method referenced by IMF statistics deparment appear to be:
Central Product Classification (Class Level), See Table1, page 11: Table 1. 
http://www.imf.org/external/pubs/ft/gfs/manual/pdf/templatedata.pdf

based on:
CPC v2: http://unstats.un.org/unsd/cr/registry/docs/CPCv2_structure.pdf
and: 
http://unstats.un.org/unsd/cr/registry/regcst.asp?Cl=27

2) EITI reports include no structured commodity lists. There will therefore be need for including unstructured entries under commodity type as well.

**Comment by timgdavies** [comment]
Our best bet here might be to allow that commodities can be identifier by a number of different concept schemes, drawing a distinction in our data between **recognised concept schemes** (e.g. IMF) and **local concept schemes** (e.g. the free text labels that are given).

This way, we would generally have two columns for commodity:

#commodity and #commodity+code

And might anticipate values for #commodity+code such as:

* imf/1101 
* unstat/12010 

Or custom taxonomies like:

* local/oil

And if #commodity+code is blank, we could look to generate a custom identifier, but which rather than being unstructured, would still be created as a skos:Concept which can later be mapped against one of the other taxonomies.

**Comment by pudo** [comment]
Sorry to stumble in here, but I'd be really interested in such a taxonomy name-spacing thing, we've been discussing very similar ideas over at OpenSpending (see [this gist](https://gist.github.com/pudo/d810d91778e73e991b48)). Perhaps something that could live in its own repo?

**Comment by timgdavies** [comment]
@pudo I'd be very interested in working on this in a shared way. 

It might also be something the Joined Up Data Alliance project could be invited to support in some way...

**Comment by pwalsh** [comment]
This is definitely interesting, for OpenSpending and as a general purpose pattern for taxonomies.

**Comment by anderspeders** [comment]
I think this could work. However we should expect that /local woud be the predominant type submitted. 

These are the +200 types submitted across EITI reports and in RC.org: 
https://docs.google.com/spreadsheets/d/12UCQA422r5Dg3wruUmYHL2SCLdDrlesCPcm2tHD8Yu4/edit#gid=639810343

**Comment by timgdavies** [comment]
I've looked into an approach to reconcile a list against the UN CPC here: https://github.com/NRGI/resource-projects-etl/tree/master/process/codelist-commodity-match

I've not got the domain expertise to carry out this reconciliation, so it might be a task that needs some NRGI expert input if we want to map against a good authority list most of the time.

For the initial version though I think we are going to be working with local identifiers.

**Comment by timgdavies** [comment]
For now we've agreed to use free-text for most commodities, but to introduce a field for determining whether the commodity type is 'Oil and Gas' or 'Mining'
