### ISSUE TITLE
Bring Phase 2 live

### ISSUE THREAD

**Issue by mattfullerton** [NRGI/ResourceProjects.org#190]
- [ ] Check master cluster deployment stability @aismail 
- [ ] Restore login requirement for ETL if easily possible in routes @mattfullerton

**Comment by davidmihalyi** [comment]
@aismail please make sure hat our master branch is also stable not only the staging one.

**Comment by aismail** [comment]
@davidmihalyi ack, will be checking it today

**Comment by davidmihalyi** [comment]
@KseniyaKuprina : when are you back from leave?

**Comment by KseniyaKuprina** [comment]
@davidmihalyi getting back on Monday

**Comment by aismail** [comment]
@davidmihalyi I will double check the servers, but I'm afraid the problem was specific to staging. 

In-depth explanation: we have 2 recurring failures that happen to affect the 3 nodes that host the deployments:
* number of inodes gets filled up
* nodes are dropped from the cluster (I think it's a Zookeeper problem, still investigating)

Since staging was previously deployed only on one node, if that particular node had problems, it went down. The production deploy is on 3 nodes, so it was never directly affected.

The other staging-specific problem that plagued us was that the MongoDB password was changed to something without updating the config, so that doesn't affect staging either.

I will double check the servers, but what we agreed on Slack is a bit better: offer ops assistance coupled with a manual deploy this time. I will need a pull request to review with the changes that are going in production, and we may have to do a quick plan of how to roll things back if anything goes wrong. Do you think that's a good idea? Thank you!
