### ISSUE TITLE
Modelling notes: Provenance

### ISSUE THREAD

**Issue by timgdavies** [NRGI/resourceprojects.org#4]
Many of the pieces of the puzzle we are dealing with come from different sources, and we need to track their provenance.

A Linked Data back-end provides two main approaches to managing provenance:

**Named graphs** in which all the statements from a given source are loaded into their own graph (segmented part of the data store), and statements about that graph as a whole recorded somewhere in the system (usually a provenance graph). 

 This minimises the quantity of provenance information, but introduces some complexity in managing querying across graphs with certain triple stores, and with OntoWiki - so would need more investigation.  

http://patterns.dataincubator.org/book/named-graphs.html  

**Reification** in which new statements are added about the triples in a store, with each individual triple annotated with provenance information.  

This approach has a storage overhead, but allows the provenance of any statement to be explored.   

http://patterns.dataincubator.org/book/reified-statement.html

**Comment by timgdavies** [comment]
From brief investigation here: https://groups.google.com/forum/#!topic/ontowiki-user/_vBdNKoJ5Fg

Ontowiki stores a revision history on a special Virtuoso SQL table, rather than as reified triples - and only for things edited through the interface.

We could:

* Use a similar model for our meta-data about data we load to a triple store (not very portable across different backends)
* Have a process to materialise the data from the Virutoso SQL table into reified triples in a graph

**Comment by anderspeders** [comment]
This might be a rabbit hole of mine or simply a misunderstanding.

I wonder: For simple fact extracted from PDF, would a viable option be: to store the PDF in AWS as permanent source with associated metadata?

On *provenance and timeliness* I am curious to hear how the following issues affect our approach: 
- The majority of sources remain for the time being PDFs (majority of government sources, EITI data) or flat files (EITI data, extractive discsloures). Thus limited use of live API's etc. 

- Likewise the nature or cycle of projects is long term, rather than short term: A project might change co-owner or operator from year to year, but often more rarely than that. That could reduce the demand for timely live data sources and make an annual data collection cycle a realistic option - which would be remarkably different to Open Corporates, for example.

Thoughts?

**Comment by timgdavies** [comment]
So - the key need here is for us to be able to, for any statement in our data, work out where it came from.

Storing the PDF is a good thing, but we also need to work out how information from the PDF ended up in the data store, and what has happened to it since then. Without this, it is hard to, from a project record, trace back all the different sources of information that have come together to make it.

**Comment by byndcivilization** [comment]
We talked a bit about this during the sprint in march. Remember this was primarily around python scripts to retrieve info from SEC database. Our idea was to use hashes to encode queries and results. This way you could test new query against existing query list to make sure you're documenting repeated pulls as well as testing for new results. 

Not sure if this would work for a more diverse ETL ecosystem than a single entry point. Also not sure what the risk of collision is here.

**Comment by anderspeders** [comment]
There could be some sort if decision tree for sourcing: 
- API from government website - first choice
- When not available as API - a link to public data source - second choice etc.

**Comment by timgdavies** [comment]
See https://github.com/NRGI/resourceprojects.org-frontend/issues/20 for more details of the current approach.

**Comment by timgdavies** [comment]
We are now handling this in front-end.

We have an approach to tagging the type of source, and to including more source information.
